### ISSUE TITLE
请教一下如何定制自己的机器信息呢？

### ISSUE THREAD

**Issue by liangzhaoliang95** [hackintosh-efi/ASUS-PRIME-Z690-P-D4-OpenCore#1]
请教一下如何定制自己的机器信息呢？我使用ocat工具一键生成，但是发现整个config.plist被污染了

**Comment by WuLongMiTaoLaiYiDa** [comment]
1.确保OCAT对应的是目前的0.8.8版本
2.打开OCAT选择左侧的PI --  选择 右侧窗口的 SystemProductName -- 选择 MacPro7,1机型 --选择窗口旁边的 生成按钮
3.点击窗口上方的 蓝色 保存 按钮
首先要确保bios里的设置正确，其次用RU.efi解锁过bios cfglock ，按照上述方式放入三码应该就可以使用了，如果硬件配置不同，例如无线网卡是英特尔的话需要自行添加驱动

**Comment by liangzhaoliang95** [comment]
谢谢，已经搞好了，不过有一个问题，你提供的config.plist通过ocat读取的时候会提示报错，一旦点保存就会文件污染

**Comment by liangzhaoliang95** [comment]
@WuLongMiTaoLaiYiDa 经过我的测试，你提供的这个EFI是不是只驱动了4个USB口啊，主板上后面的USB只有一个能用

**Comment by WuLongMiTaoLaiYiDa** [comment]
因机箱不同，大部分情况下,USB驱动不具备通用性，背面的USB3和C口我都定制了的，我机箱正面接口比较多，看看USB定制教程自己定下哦。

**Comment by liangzhaoliang95** [comment]
背面只有一个usb3能用，反而是机箱上的三个口都能用
