### ISSUE TITLE
声卡没有声音

### ISSUE THREAD

**Issue by seaurching** [hackintosh-efi/ASUS-PRIME-Z690-P-D4-OpenCore#2]
我看你配置的声卡layout-id为11，我改成了11之后，接上hdmi输出没有声音，换成66就有声音。我和你是同样的主板，都是alc897的声卡，咋布局id还不一样？

**Comment by WuLongMiTaoLaiYiDa** [comment]
都记不得最早的版本用的什么ID了，用66是对的哦

**Comment by seaurching** [comment]
接 HDMI 配置开机音效可以吗？我配置的后没有声音
